hw 15, First commit.Imitation and getting started with generics (and collections)
Shubertov/LemonSchool_repository pull request #3
Opened 2023-04-24 12:48 UTC by Shubertov

First commit.Imitation and getting started with generics (and collections)

2023-04-24 18:55 UTC, Bibi4kovIgor requested changes
Необхідно внести виправлення у зазначені місця

2023-04-24 18:55 UTC, Bibi4kovIgor commented on src/main/java/edu/lemonschool/practicework15/Basket.java
> +    public int quantityProduct(T product){
Не до кінця зрозумів цей метод. Яка його ціль?

2023-04-24 18:55 UTC, Bibi4kovIgor commented on src/main/java/edu/lemonschool/practicework15/HardwareStore.java
> +//    protected String router;
Коментарі слід видалити перед завантаженням до репозиторію

2023-04-24 18:55 UTC, Bibi4kovIgor commented on src/main/java/edu/lemonschool/practicework15/HardwareStore.java
> +        return null;
Не зрозуміла ціль метода?
"return null"?

2023-04-24 18:55 UTC, Bibi4kovIgor commented on src/main/java/edu/lemonschool/practicework15/Main.java
> +        System.out.println(printer);
Краще додати всі об'єкти у ліст і з нього вже в циклі виводити значення

2023-04-24 18:55 UTC, Bibi4kovIgor commented on src/main/java/edu/lemonschool/practicework15/Processor.java
> +    public void processWork(String Info){
System.out/Scanner.in слід розташовувати виключно в спеціальних для того створених методах.
В даному випадку, краще повертати значення в методі

2023-04-24 18:55 UTC, Bibi4kovIgor commented on src/main/java/edu/lemonschool/practicework15/Printer.java
> +        System.out.println(page);
System.out/Scanner.in слід розташовувати виключно в спеціальних для того створених методах.
В даному випадку, краще повертати значення в методі

2023-04-24 18:55 UTC, Bibi4kovIgor commented on src/main/java/edu/lemonschool/practicework15/Scanner.java
> +        System.out.println(page);
System.out/Scanner.in слід розташовувати виключно в спеціальних для того створених методах.
В даному випадку, краще повертати значення в методі

2023-04-25 18:54 UTC, Shubertov reviewed
Виправив проблеми. Та покращив код!

2023-04-25 18:54 UTC, Shubertov commented on src/main/java/edu/lemonschool/practicework15/Basket.java
> +    public int quantityProduct(T product){
Прибрав його!

2023-04-25 18:54 UTC, Shubertov commented on src/main/java/edu/lemonschool/practicework15/HardwareStore.java
> +//    protected String router;
Видалив коментарі!

2023-04-25 18:54 UTC, Shubertov commented on src/main/java/edu/lemonschool/practicework15/HardwareStore.java
> +        return null;
Як на мене нептотрібний метод. Не знаю, як його використати, тому прибрав!

2023-04-25 18:54 UTC, Shubertov commented on src/main/java/edu/lemonschool/practicework15/Main.java
> +        System.out.println(printer);
Зроблено!

2023-04-25 18:54 UTC, Shubertov commented on src/main/java/edu/lemonschool/practicework15/Printer.java
> +        System.out.println(page);
Перероблено!

2023-04-25 18:54 UTC, Shubertov commented on src/main/java/edu/lemonschool/practicework15/Processor.java
> +    public void processWork(String Info){
Перероблено!

2023-04-25 18:54 UTC, Shubertov commented on src/main/java/edu/lemonschool/practicework15/Scanner.java
> +        System.out.println(page);
Перероблено!

2023-04-28 21:13 UTC, Bibi4kovIgor approved these changes

2023-04-28 21:13 UTC, merged